INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 0, 'primary', 'MEMBROS DAS FORÇAS ARMADAS, POLICIAIS E BOMBEIROS MILITARES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 1, 'primary', 'MEMBROS SUPERIORES DO PODER PÚBLICO, DIRIGENTES DE ORGANIZAÇÕES DE INTERESSE PÚBLICO E DE EMPRESAS, GERENTES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 2, 'primary', 'PROFISSIONAIS DAS CIÊNCIAS E DAS ARTES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 3, 'primary', 'TÉCNICOS DE NIVEL MÉDIO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 4, 'primary', 'TRABALHADORES DE SERVIÇOS ADMINISTRATIVOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 5, 'primary', 'TRABALHADORES DOS SERVIÇOS, VENDEDORES DO COMÉRCIO EM LOJAS E MERCADOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 6, 'primary', 'TRABALHADORES AGROPECUÁRIOS, FLORESTAIS E DA PESCA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 7, 'primary', 'TRABALHADORES DA PRODUÇÃO DE BENS E SERVIÇOS INDUSTRIAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 8, 'primary', 'TRABALHADORES DA PRODUÇÃO DE BENS E SERVIÇOS INDUSTRIAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', 9, 'primary', 'TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO');

INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', '01', 'secondary', 'MEMBROS DAS FORÇAS ARMADAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', '02', 'secondary', 'POLICIAIS MILITARES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('0', '03', 'secondary', 'BOMBEIROS MILITARES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('1', '11', 'secondary', 'MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('1', '12', 'secondary', 'DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('1', '13', 'secondary', 'DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('1', '14', 'secondary', 'GERENTES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '20', 'secondary', 'PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '21', 'secondary', 'PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '22', 'secondary', 'PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '23', 'secondary', 'PROFISSIONAIS DO ENSINO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '24', 'secondary', 'PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '25', 'secondary', 'PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '26', 'secondary', 'COMUNICADORES, ARTISTAS E RELIGIOSOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('2', '27', 'secondary', 'PROFISSIONAIS EM GASTRONOMIA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '30', 'secondary', 'TÉCNICOS POLIVALENTES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '31', 'secondary', 'TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '32', 'secondary', 'TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '33', 'secondary', 'PROFESSORES LEIGOS E DE NÍVEL MÉDIO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '34', 'secondary', 'TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '35', 'secondary', 'TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '37', 'secondary', 'TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('3', '39', 'secondary', 'OUTROS TÉCNICOS DE NÍVEL MÉDIO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('4', '41', 'secondary', 'ESCRITURÁRIOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('4', '42', 'secondary', 'TRABALHADORES DE ATENDIMENTO AO PÚBLICO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('5', '51', 'secondary', 'TRABALHADORES DOS SERVIÇOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('5', '52', 'secondary', 'VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('6', '61', 'secondary', 'PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('6', '62', 'secondary', 'TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('6', '63', 'secondary', 'PESCADORES E EXTRATIVISTAS FLORESTAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('6', '64', 'secondary', 'TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '71', 'secondary', 'TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '72', 'secondary', 'TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '73', 'secondary', 'TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '74', 'secondary', 'MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '75', 'secondary', 'JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '76', 'secondary', 'TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '77', 'secondary', 'TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '78', 'secondary', 'TRABALHADORES DE FUNÇÕES TRANSVERSAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('7', '79', 'secondary', 'TRABALHADORES DO ARTESANATO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '81', 'secondary', 'TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '82', 'secondary', 'TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '83', 'secondary', 'TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '84', 'secondary', 'TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '86', 'secondary', 'OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('8', '87', 'secondary', 'OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('9', '91', 'secondary', 'TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('9', '95', 'secondary', 'POLIMANTENEDORES');
INSERT INTO iddacultura_useroccupation (parent, code, type, name) VALUES ('9', '99', 'secondary', 'OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO');
